apps/company/urls.py
from django.urls import path
from .views import CompanyDetailView, CarListView, CarCreateView, RequsetCarListView, TrackOfferListView

urlpatterns = [
    path('', CompanyDetailView.as_view()),
    path('cars/', CarListView.as_view()),
    path('cars/create/', CarCreateView.as_view()),
    path('requests/', RequsetCarListView.as_view()),
    path('routes/', TrackOfferListView.as_view()),
]

apps/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('apps.passenger.urls')),
    path('rent/', include('apps.order.urls')),
    path('company/', include('apps.company.urls')),
]

conductor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('apps.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/company/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from sorl.thumbnail.fields import ImageField
from apps.utils.models import DateAddDateChangeMixin

car_types = (
    (1, 'Автобус'),
    (2, 'Троллейбус'),
    (3, 'Трамвай'),
    (4, 'Маршрутное транспортное средство'),
)


class Company(models.Model, DateAddDateChangeMixin):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Название', max_length=255)

    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

    def __str__(self):
        return self.name


# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Company.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_company(sender, instance, **kwargs):
    if hasattr(instance, 'company'):
        instance.company.save()


class Car(models.Model, DateAddDateChangeMixin):
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='Название компании', max_length=50)
    reg_num = models.CharField(verbose_name='Регистрационный номер', max_length=10)
    verify = models.BooleanField(verbose_name='Верифицировано', default=False)

    class Meta:
        verbose_name = 'Транспортное средство'
        verbose_name_plural = 'Транспортные средства'

    def __str__(self):
        return self.name


class CarImage(models.Model, DateAddDateChangeMixin):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    image = ImageField(verbose_name='Картинка', upload_to='uploads/cars/')

apps/company/forms.py
from django import forms
from .models import Car


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = ['reg_num', 'name']
        widgets = {
            'reg_num': forms.TextInput(attrs={'class': 'mdl-textfield__input'}),
            'name': forms.TextInput(attrs={'class': 'mdl-textfield__input'}),
        }

apps/company/views.py
from django.views.generic import DetailView, ListView, CreateView
from .models import Company, Car
from .forms import CarForm
from apps.order.models import RequestCar
from apps.track.models import TrackOffer


class CompanyDetailView(DetailView):
    model = Company

    def get_object(self, queryset=None):
        if hasattr(self.request.user, 'company'):
            return self.request.user.company
        return None


class CarListView(ListView):
    model = Car
    template_name = 'company/car_list.html'

    def get_queryset(self):
        if hasattr(self.request.user, 'company'):
            return self.request.user.company.car_set.all()
        return None


class CarCreateView(CreateView):
    model = Car
    form_class = CarForm
    template_name = 'company/car_create.html'
    success_url = '/company/cars/'

    def form_valid(self, form):
        form.instance.company = self.request.user.company
        return super(CarCreateView, self).form_valid(form)


class RequsetCarListView(ListView):
    model = RequestCar
    template_name = 'company/requestcar_list.html'


class TrackOfferListView(ListView):
    model = TrackOffer
    template_name = 'company/trackoffer_list.html'

templates/company/car_create.html
{% extends 'company/company_detail.html' %}
{% block content %}
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--12-col" style="background: rgba(255,255,255,0.7); padding: 20px; box-shadow: 0 0 10px 0 rgba(0,0,0,0.3)">
            <h3>Добавить транспортное средство</h3>
            <form action="." method="post">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    {{ form.name }}
                    <label class="mdl-textfield__label" for="id_name">Название</label>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    {{ form.reg_num }}
                    <label class="mdl-textfield__label" for="id_reg_num">Регистрационный номер</label>
                </div>
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">
                    Сохранить
                </button>
            </form>
        </div>
    </div>
{% endblock %}

templates/company/car_list.html
{% extends 'company/company_detail.html' %}
{% block content %}
    <div class="mdl-grid">
        {% for object in object_list %}
            <div class="mdl-cell mdl-cell--4-col">
                <div class="demo-card-wide mdl-card mdl-shadow--2dp">
                    <div class="mdl-card__title">
                        <h2 class="mdl-card__title-text">{{ object.name }}</h2>
                    </div>
                    <div class="mdl-card__supporting-text">
                        {{ object.reg_num }}
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="mdl-cell mdl-cell--12-col">
            <a href="/company/cars/create/" class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored">
                <i class="material-icons">add</i>
            </a>
        </div>
    </div>
{% endblock %}

templates/company/company_detail.html
{% extends 'base.html' %}
{% block nav %}
    <a class="mdl-navigation__link" href="/company/">Личный кабинет</a>
    <a class="mdl-navigation__link" href="/company/cars/">Автомобили</a>
    <a class="mdl-navigation__link" href="/company/requests/">Заявки</a>
    <a class="mdl-navigation__link" href="/company/routes/">Маршруты</a>
{% endblock %}
{% block content %}
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--12-col" style="background: rgba(255,255,255,0.7); padding: 20px; box-shadow: 0 0 10px 0 rgba(0,0,0,0.3)">
            <h3>{{ object.name }}</h3>
        </div>
    </div>
{% endblock %}

templates/company/requestcar_list.html
{% extends 'company/company_detail.html' %}
{% block content %}
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--12-col" style="background: rgba(255,255,255,0.7); padding: 20px; box-shadow: 0 0 10px 0 rgba(0,0,0,0.3)">
            <ul class="mdl-list">
                {% for object in object_list %}
                    <li class="mdl-list__item">
                        <span class="mdl-list__item-primary-content">
                            <i class="material-icons mdl-list__item-avatar">person</i>
                            <span>{{ object.passenger.first_name }} {{ object.passenger.last_name }}</span>
                        </span>
                        <span class="mdl-list__item-primary-content">{{ object.capacity }}</span>
                        <span class="mdl-list__item-primary-content">{{ object.date_start }}</span>
                        <span class="mdl-list__item-primary-content">{{ object.date_end }}</span>
                        <span class="mdl-list__item-secondary-content">
                            <a href="/company/reqeusts/{{ object.id }}/offer/" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
                                Предложить транспорт
                            </a>
                        </span>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/company/trackoffer_list.html
{% extends 'company/company_detail.html' %}
{% block content %}
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--12-col" style="background: rgba(255,255,255,0.7); padding: 20px; box-shadow: 0 0 10px 0 rgba(0,0,0,0.3)">
            <h3>Запросы на маршрут</h3>
            <ul class="mdl-list">
                {% for object in object_list %}
                    <li class="mdl-list__item">
                        <span class="mdl-list__item-primary-content">
                            <i class="material-icons mdl-list__item-avatar">person</i>
                            <span>{{ object.passenger.first_name }} {{ object.passenger.last_name }}</span>
                        </span>
                        <span class="mdl-list__item-primary-content">{{ object.departure }}</span>
                        <span class="mdl-list__item-primary-content">{{ object.destination }}</span>
                        <span class="mdl-list__item-primary-content">{{ object.date }}</span>
                        <span class="mdl-list__item-secondary-content">
                            <a href="/company/reqeusts/{{ object.id }}/offer/" class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored">
                                Предложить транспорт
                            </a>
                        </span>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}