apps/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('apps.passenger.urls')),
    path('rent/', include('apps.order.urls')),
    path('company/', include('apps.company.urls')),
]

conductor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('apps.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/track/models.py
import datetime
from django.db import models
from apps.utils.models import DateAddDateChangeMixin
from apps.company.models import Car
from apps.passenger.models import User


class Track(models.Model, DateAddDateChangeMixin):
    name = models.CharField(verbose_name='Название', max_length=200)
    departure = models.CharField(verbose_name='Пункт отрпавления', max_length=200)
    destination = models.CharField(verbose_name='Пункт назначения', max_length=200)
    date_start = models.DateTimeField(verbose_name='Время отправления', default=datetime.datetime.now)
    date_end = models.DateTimeField(verbose_name='Время прибытия', default=datetime.datetime.now)

    class Meta:
        verbose_name = 'Маршрут'
        verbose_name_plural = 'Маршруты'

    def __str__(self):
        return self.name


class TrackCar(models.Model, DateAddDateChangeMixin):
    track = models.ForeignKey(Track, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Авто на маршруте'
        verbose_name_plural = 'Авто на маршруте'

    def __str__(self):
        return ' -> '.join([self.track, self.car])


class TrackOffer(models.Model, DateAddDateChangeMixin):
    passenger = models.ForeignKey(User, on_delete=models.CASCADE)
    departure = models.CharField(verbose_name='Пункт отрпавления', max_length=200)
    destination = models.CharField(verbose_name='Пункт назначения', max_length=200)
    date = models.DateField(verbose_name='Дата маршрута', default=datetime.date.today)
    time_range = models.CharField(verbose_name='Временной диапазон', max_length=50, blank=True)
    count = models.PositiveIntegerField(verbose_name='Количество человек', default=1)

    class Meta:
        verbose_name = 'Заказ маршрута'
        verbose_name_plural = 'Заказы маршрута'

    def __str__(self):
        return ' -> '.join([self.passenger.username, self.departure, self.destination])

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Автомаяк</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,700&display=swap&subset=cyrillic-ext"
          rel="stylesheet">
    <link rel="stylesheet" href="/media/css/main.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-amber.min.css">
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
</head>
<body>
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
            <!-- Title -->
            <span class="mdl-layout-title">
                <img src="/media/images/logo_alt.png" height="80px" alt="">
                <img src="/media/images/optional.png" height="80px" alt="">
            </span>
            <!-- Add spacer, to align navigation to the right -->
            <div class="mdl-layout-spacer"></div>
            <!-- Navigation. We hide it in small screens. -->
            <nav class="mdl-navigation mdl-layout--large-screen-only">
                {% block nav %}
                    <a class="mdl-navigation__link" href="/">Поиск маршрута</a>
                    <a class="mdl-navigation__link" href="/rent/">Аренда транспорта</a>
                {% endblock %}
            </nav>
            <nav class="mdl-navigation">
                <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="user-menu">
                    <i class="material-icons">personal</i>
                </button>
                <nav class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" data-mdl-for="user-menu">
                    <a href="/company/" class="mdl-menu__item">Перейти в личный кабинет</a>
                    <a href="/logout/" class="mdl-menu__item">Выход</a>
                </nav>
            </nav>
        </div>
    </header>
    <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">
            <img class="mdl-logo" src="/media/images/logo.png" alt="logo" width="150px">
        </span>
        <nav class="mdl-navigation">
            <a class="mdl-navigation__link" href="/">Поиск маршрута</a>
            <a class="mdl-navigation__link" href="/rent/">Аренда транспорта</a>
        </nav>
    </div>
    <main class="mdl-layout__content" style="background: url('/media/images/bus.png') 50% 50%/cover no-repeat;">
        <div class="page-content">
            {% block content %}

            {% endblock %}
        </div>
    </main>
    <footer class="mdl-mini-footer">
        <div class="mdl-mini-footer__left-section">
            <div class="mdl-logo">© Прагматика 2019 г.</div>
        </div>
    </footer>
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--12-col" style="background: rgba(255,255,255,0.7); padding: 20px; box-shadow: 0 0 10px 0 rgba(0,0,0,0.3)">
            <h3>Найти туристический маршрут</h3>
            <form action="." method="post">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    {{ form.departure }}
                    <label class="mdl-textfield__label" for="id_departure">Откуда</label>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    {{ form.destination }}
                    <label class="mdl-textfield__label" for="id_destination">Куда</label>
                </div>
                {#                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">#}
                {#                    <input class="mdl-textfield__input" type="text" id="sample3">#}
                {#                    <label class="mdl-textfield__label" for="sample3">Дата</label>#}
                {#                </div>#}
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">
                    Найти
                </button>
                {% if track %}
                    <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit" name="request">
                        Оставить заявку
                    </button>
                {% endif %}
            </form>
            {{ track|safe }}
            {% if map %}
                <iframe src="https://yandex.ru/map-widget/v1/-/CGACmTIX" width="100%" height="400" frameborder="1" allowfullscreen="true"></iframe>
            {% endif %}
        </div>
    </div>
{% endblock %}