apps/order/urls.py
from django.urls import path
from .views import RequestCarCreateView


urlpatterns = [
    path('', RequestCarCreateView.as_view()),
]

apps/urls.py
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('apps.passenger.urls')),
    path('rent/', include('apps.order.urls')),
    path('company/', include('apps.company.urls')),
]

conductor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('apps.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/order/models.py
import datetime
from django.db import models
from django.contrib.auth.models import User
from apps.company.models import Car
from apps.passenger.models import Passenger
from apps.utils.models import DateAddDateChangeMixin


class OrderCar(models.Model, DateAddDateChangeMixin):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    passenger = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(verbose_name='Стоимость', default=0, max_digits=12, decimal_places=2)
    date_start = models.DateTimeField(verbose_name='Дата начала', default=datetime.datetime.now)
    date_end = models.DateTimeField(verbose_name='Дата окончания', default=datetime.datetime.now)

    class Meta:
        verbose_name = 'Заказ авто'
        verbose_name_plural = 'Заказы авто'

    def __str__(self):
        return ' -> '.join([self.passenger.__str__(), self.car])


class RequestCar(models.Model, DateAddDateChangeMixin):
    passenger = models.ForeignKey(User, on_delete=models.CASCADE)
    capacity = models.PositiveIntegerField(verbose_name='Вместимость человек', default=1)
    date_start = models.DateTimeField(verbose_name='Дата начала', default=datetime.datetime.now)
    date_end = models.DateTimeField(verbose_name='Дата окончания', default=datetime.datetime.now)

    class Meta:
        verbose_name = 'Запрос авто'
        verbose_name_plural = 'Запросы авто'

    def __str__(self):
        return ' -> '.join([self.passenger.__str__(), self.date_start.__str__()])


class OfferCar(models.Model, DateAddDateChangeMixin):
    request = models.ForeignKey(RequestCar, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    price = models.DecimalField(verbose_name='Стоимость', default=0, max_digits=12, decimal_places=2)

    class Meta:
        verbose_name = 'Предложение авто'
        verbose_name_plural = 'Предложения авто'

    def __str__(self):
        return ' -> '.join([self.request, self.car])

apps/order/forms.py
from django import forms
from .models import RequestCar


class RequestCarForm(forms.ModelForm):
    class Meta:
        model = RequestCar
        fields = ['capacity', 'date_start', 'date_end']
        widgets = {
            'capacity': forms.NumberInput(attrs={'class': 'mdl-textfield__input'}),
            'date_start': forms.DateInput(attrs={'class': 'mdl-textfield__input'}),
            'date_end': forms.DateInput(attrs={'class': 'mdl-textfield__input'}),
        }

apps/order/views.py
from django.views.generic import ListView, CreateView
from .models import RequestCar
from .forms import RequestCarForm


class RequestCarCreateView(CreateView):
    model = RequestCar
    template_name = 'order/requestcar_create.html'
    form_class = RequestCarForm
    success_url = '/rent/success'

    def form_valid(self, form):
        form.instance.passenger = self.request.user
        return super(RequestCarCreateView, self).form_valid(form)

templates/order/requestcar_create.html
{% extends 'base.html' %}
{% block content %}
    <div class="mdl-grid">
        <div class="mdl-cell mdl-cell--12-col" style="background: rgba(255,255,255,0.7); padding: 20px; box-shadow: 0 0 10px 0 rgba(0,0,0,0.3)">
            <h3>Заказать транспорт</h3>
            <form action="." method="post">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}">
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    {{ form.capacity }}
                    <label class="mdl-textfield__label" for="id_capacity">Количество человек</label>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    {{ form.date_start }}
                    <label class="mdl-textfield__label" for="id_date_start">Дата начала</label>
                </div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                    {{ form.date_end }}
                    <label class="mdl-textfield__label" for="id_date_end">Дата окончания</label>
                </div>
                <button class="mdl-button mdl-js-button mdl-button--raised mdl-button--colored" type="submit">
                    Сохранить
                </button>
            </form>
        </div>
    </div>
{% endblock %}